data_source_class_type: ImplicitronDataSource
model_factory_class_type: ImplicitronModelFactory
optimizer_factory_class_type: ImplicitronOptimizerFactory
training_loop_class_type: ImplicitronTrainingLoop
disable_testing: true
disable_validation: true
seed: 42
detect_anomaly: false
exp_dir: /checkpoint/animeshkarnewar/holo_diffusion/release_experiments/release_holo_diffusion_0529_ldm_multigpu_nodec_wbg/release_holo_diffusion_0529_ldm_multigpu_nodec_wbg_d_d_category_hydrant_m_m_image_feature_extractor_class_type_ResNetFeatureExtractor
hydra:
  run:
    dir: .
  output_subdir: null
  mode: RUN
data_source_ImplicitronDataSource_args:
  dataset_map_provider_class_type: JsonIndexDatasetMapProviderV2
  data_loader_map_provider_class_type: SequenceDataLoaderMapProvider
  dataset_map_provider_JsonIndexDatasetMapProviderV2_args:
    category: hydrant
    subset_name: fewview_dev
    dataset_root: /datasets01/co3dv2/080422
    test_on_train: true
    only_test_set: false
    load_eval_batches: true
    num_load_workers: 4
    n_known_frames_for_test: 0
    dataset_class_type: JsonIndexDataset
    path_manager_factory_class_type: PathManagerFactory
    dataset_JsonIndexDataset_args:
      limit_to: 0
      limit_sequences_to: 500
      pick_sequence: []
      exclude_sequence: []
      limit_category_to: []
      load_images: true
      load_depths: true
      load_depth_masks: true
      load_masks: true
      load_point_clouds: false
      max_points: 0
      mask_images: false
      mask_depths: false
      image_height: 800
      image_width: 800
      box_crop: true
      box_crop_mask_thr: 0.4
      box_crop_context: 0.3
      remove_empty_masks: true
      n_frames_per_sequence: -1
      seed: 0
      sort_frames: false
    path_manager_factory_PathManagerFactory_args:
      silence_logs: true
  data_loader_map_provider_SequenceDataLoaderMapProvider_args:
    batch_size: 33
    num_workers: 5
    dataset_length_train: 8000
    dataset_length_val: 1
    dataset_length_test: 0
    train_conditioning_type: SAME
    val_conditioning_type: SAME
    test_conditioning_type: SAME
    images_per_seq_options:
    - 33
    sample_consecutive_frames: false
    consecutive_frames_max_gap: 0
    consecutive_frames_max_gap_seconds: 0.1
model_factory_ImplicitronModelFactory_args:
  resume: true
  model_class_type: HoloDiffusionModel
  resume_epoch: -1
  force_resume: false
  model_HoloDiffusionModel_args:
    log_vars:
    - loss_rgb_psnr_fg
    - loss_rgb_psnr
    - loss_rgb_mse
    - loss_rgb_huber
    - loss_depth_abs
    - loss_depth_abs_fg
    - loss_mask_neg_iou
    - loss_mask_bce
    - loss_mask_beta_prior
    - loss_eikonal
    - loss_density_tv
    - loss_depth_neg_penalty
    - loss_autodecoder_norm
    - loss_prev_stage_rgb_mse
    - loss_prev_stage_prev_stage_rgb_mse
    - loss_prev_stage_prev_stage_prev_stage_rgb_mse
    - loss_prev_stage_prev_stage_prev_stage_prev_stage_rgb_mse
    - loss_prev_stage_prev_stage_prev_stage_prev_stage_prev_stage_rgb_mse
    - loss_prev_stage_rgb_psnr_fg
    - loss_prev_stage_rgb_psnr
    - loss_prev_stage_mask_bce
    - loss_prev_stage_prev_stage_mask_bce
    - loss_prev_stage_prev_stage_prev_stage_mask_bce
    - objective
    - epoch
    - sec/it
    mask_images: true
    mask_depths: true
    render_image_width: 256
    render_image_height: 256
    mask_threshold: 0.5
    output_rasterized_mc: true
    bg_color:
    - 1.0
    - 1.0
    - 1.0
    num_passes: 2
    chunk_size_grid: 163840
    render_features_dimensions: 3
    tqdm_trigger_threshold: 100
    n_train_target_views: 10
    sampling_mode_training: mask_sample
    sampling_mode_evaluation: full_grid
    global_encoder_class_type: null
    raysampler_class_type: AdaptiveRaySampler
    renderer_class_type: HoloMultiPassEmissionAbsorptionRenderer
    image_feature_extractor_class_type: ResNetFeatureExtractor
    view_pooler_enabled: true
    implicit_function_class_type: HoloVoxelGridImplicitFunction
    view_metrics_class_type: ViewMetrics
    regularization_metrics_class_type: RegularizationMetrics
    loss_weights:
      loss_rgb_mse: 1.0
      loss_prev_stage_rgb_mse: 1.0
      loss_prev_stage_prev_stage_rgb_mse: 1.0
      loss_prev_stage_prev_stage_prev_stage_rgb_mse: 1.0
      loss_prev_stage_prev_stage_prev_stage_prev_stage_rgb_mse: 1.0
      loss_mask_bce: 0.0
      loss_prev_stage_mask_bce: 0.0
      loss_prev_stage_prev_stage_mask_bce: 0.0
    raysampler_AdaptiveRaySampler_args:
      n_pts_per_ray_training: 64
      n_pts_per_ray_evaluation: 64
      n_rays_per_image_sampled_from_mask: 1024
      n_rays_total_training: null
      stratified_point_sampling_training: true
      stratified_point_sampling_evaluation: false
      scene_extent: 4.0
      scene_center:
      - 0.0
      - 0.0
      - 0.0
    renderer_HoloMultiPassEmissionAbsorptionRenderer_args:
      raymarcher_class_type: EmissionAbsorptionRaymarcher
      n_pts_per_ray_fine_training: 64
      n_pts_per_ray_fine_evaluation: 64
      stratified_sampling_coarse_training: true
      stratified_sampling_coarse_evaluation: false
      append_coarse_samples_to_fine: true
      density_noise_std_train: 1.0
      return_weights: false
      raymarcher_EmissionAbsorptionRaymarcher_args:
        surface_thickness: 1
        bg_color:
        - 1.0
        - 1.0
        - 1.0
        replicate_last_interval: false
        background_opacity: 10000000000.0
        density_relu: true
        blend_output: false
    image_feature_extractor_ResNetFeatureExtractor_args:
      name: resnet34
      pretrained: true
      stages:
      - 1
      - 2
      - 3
      - 4
      normalize_image: true
      image_rescale: 0.32
      first_max_pool: true
      proj_dim: 16
      l2_norm: true
      add_masks: true
      add_images: true
      global_average_pool: false
      feature_rescale: 1.0
    view_pooler_args:
      feature_aggregator_class_type: AngleWeightedReductionFeatureAggregator
      view_sampler_args:
        masked_sampling: false
        sampling_mode: bilinear
      feature_aggregator_AngleWeightedReductionFeatureAggregator_args:
        exclude_target_view: true
        exclude_target_view_mask_features: true
        concatenate_output: true
        reduction_functions:
        - AVG
        - STD
        weight_by_ray_angle_gamma: 1.0
        min_ray_angle_weight: 0.1
    implicit_function_HoloVoxelGridImplicitFunction_args:
      resol: 32
      volume_extent: 8.0
      n_hidden: 128
      feature_dim: 64
      init_density_bias: 0.0001
      render_normals: true
      render_mlp_args:
        input_dims: 128
        output_feature_dims: 3
        output_vp_independent_feature_dims: 64
        feat_emb_dims: 0
        dir_emb_dims: 4
        dnet_num_layers: 4
        dnet_hidden_dim: 256
        dnet_input_skips:
        - 2
        rnet_num_layers: 1
        rnet_hidden_dim: 128
        rnet_input_skips: []
        activation_fn: LEAKYRELU
    view_metrics_ViewMetrics_args: {}
    regularization_metrics_RegularizationMetrics_args: {}
    resol: 16
    volume_extent: 8.0
    feature_size: 64
    net_3d_enabled: true
    net_3d_class_type: SimpleUnet3D
    diffusion_enabled: true
    enable_bootstrap: true
    bootstrap_prob: 0.5
    net_3d_SimpleUnet3D_args:
      image_size: 64
      in_channels: 128
      out_channels: 128
      model_channels: 64
      num_res_blocks: 2
      channel_mult:
      - 1
      - 1
      - 2
      - 4
      - 8
      attention_resolutions:
      - 4
      - 8
      num_heads: 2
      dropout: 0.0
      homogeneous_resample: true
    diffusion_args:
      beta_schedule_type: linear
      num_steps: 1000
      beta_start_unscaled: 0.0001
      beta_end_unscaled: 0.02
      model_mean_type: START_X
      model_var_type: FIXED_SMALL
      schedule_sampler_type: uniform
optimizer_factory_ImplicitronOptimizerFactory_args:
  betas:
  - 0.9
  - 0.999
  breed: Adam
  exponential_lr_step_size: 250
  gamma: 0.1
  lr: 4.0e-05
  lr_policy: MultiStepLR
  momentum: 0.9
  multistep_lr_milestones:
  - 500
  weight_decay: 0.0
  linear_exponential_lr_milestone: 200
  linear_exponential_start_gamma: 0.1
  foreach: true
  group_learning_rates: {}
training_loop_ImplicitronTrainingLoop_args:
  evaluator_class_type: ImplicitronEvaluator
  evaluator_ImplicitronEvaluator_args:
    is_multisequence: true
    camera_difficulty_bin_breaks:
    - 0.97
    - 0.98
  eval_only: false
  max_epochs: 1000
  store_checkpoints: true
  store_checkpoints_purge: 1
  test_interval: -1
  test_when_finished: false
  validation_interval: 1
  clip_grad: 0.0
  metric_print_interval: 5
  visualize_interval: 0
  visdom_env: ''
  visdom_port: 9000
  visdom_server: http://100.96.161.103
